name: Node and Docs
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CAPI: ${{ secrets.capi }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x            
      - run: 
          echo CANVAS_API="$CAPI" >> .env  
      - run: npm i
      - run: npm start
      - run: head -n -1 .env > safe.env
      - run: mv safe.env .env
      - run: cp docs/00/00.md docs/00/syllabus.md
      - run: cp pages/00/00.html pages/index.html
          node-version: 16.x
        env: 
          CANVAS_API: ${{ secrets.CANVAS_API }}
      - run: 
          echo CANVAS_API=$CANVAS_API >> .env  
      - run: npm i
      - run: npm start
  pages:
    needs: build
    name: Deploy static content to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload pages folder
          path: 'pages/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
